### ISSUE TITLE
Disappeared when wrapped in {{#if currentUser}}

### ISSUE THREAD

**Issue by leetschau** [dandv/meteor-jquery-rateit#3]
Hi, I tried to make only logged-in users can rate, as follows:

    $ meteor create rateit
    $ cd rateit
    $ meteor add accounts-ui
    $ meteor add accounts-password
    $ meteor add dandv:jquery-rateit
    $ cat rateit.html
    <head>
      <title>rateit</title>
    </head>

    <body>
      {{> hello}}
    </body>

    <template name="hello">
      {{> loginButtons}}
      {{#if currentUser}}
        <div>
          <span class="rateit">rate me!</span>
        </div>
      {{/if}}
    </template>

However, the rateit widget disappeared. After the "{{#if currentUser}}" and "{{/if}}" is removed, it appeared again.

**Comment by dandv** [comment]
That is because the `hello` template isn't re-rendered when `currentUser` becomes true. For this case, you need to structure the template like this:

```html
<template name="hello">
  {{#if currentUser}}
    Rate: {{> rating}}
  {{/if}}  
</template>

<template name="rating">
  <div class="rateit"></div>
</template>
```

And have the initialization done in the `rendered` event of the `rating` template:

```js
  // .rateit elements need to be progressively enhanced after they're created
  Template.rating.rendered = function () {
    this.$('.rateit').rateit();
  }
```

**Comment by dandv** [comment]
Updated the README to reflect this. Thanks for bringing it up!
